using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BENITEZ_MAURICIO_HW5.Models
{
    public enum ProductType
    {
        [Display(Name = "Candy")] Candy,
        [Display(Name = "Drink")] Drink,
        [Display(Name = "Popcorn")] Popcorn,
        [Display(Name = "Prepared Food")] PreparedFood,
        [Display(Name = "Other")] Other
    }
    public class Product
    {
        //PK that is autogenerated
        public Int32 ProductID { get; set; }
        //Name, IS REQUIRED
        [Required(ErrorMessage = "Product name is required")]
        [Display(Name = "Product Name")]
        public String ProductName { get; set; }

        [Display(Name = "Product Number")]

        public Int32 ProductNumber { get; set; }


        [Display(Name = "Description")]
        public String ProductDescription { get; set; }

        //PRICE IS REQUIRED
        [Display(Name = "Price")]
        [Required(ErrorMessage = "Product price is required")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public Decimal ProductPrice { get; set; }


        //Product Type
        [Display(Name = "Product Type")]
        [Required(ErrorMessage = "You must pick a product type")]
        public ProductType ProductType { get; set; }

        // Navigational Properties
        //MANY suppliers to products
        public List<Supplier> Suppliers { get; set; }
        public List<OrderDetail> OrderDetails { get; set; }

        //To prevent null errors
        public Product()
        {
            if (Suppliers == null)
            {
                Suppliers = new List<Supplier>();
            }
            if (OrderDetails == null)
            {
                OrderDetails = new List<OrderDetail>();
            }
        }


    }
}

